sudo: false
language: node_js
node_js:
  - 8
before_install:
  - npm install -g greenkeeper-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - npm run coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
